init python:
    gallery = Gallery()

    gallery.button("fiore 1") 
    gallery.image("fiore 1")
    gallery.button("fiore 2") 
    gallery.image("fiore 2") 
    gallery.button("fiore 3") 
    gallery.image("fiore 3")
    
    gallery.button("luna 1") 
    gallery.image("luna 1")
    gallery.button("luna 2") 
    gallery.image("luna 2")
    gallery.button("luna 3") 
    gallery.image("luna 3")

    gallery.button("micia 1") 
    gallery.image("micia 1")
    gallery.button("micia 2") 
    gallery.image("micia 2")
    gallery.button("micia 3") 
    gallery.image("micia 3")

    gallery.button("pinpin 1") 
    gallery.image("pinpin 1")
    gallery.button("pinpin 2") 
    gallery.image("pinpin 2")
    gallery.button("pinpin 3") 
    gallery.image("pinpin 3")

    gallery.button("valerio 1") 
    gallery.image("valerio 1")
    gallery.button("valerio 2") 
    gallery.image("valerio 2")
    gallery.button("valerio 3") 
    gallery.image("valerio 3")

    gallery.button("marco 1") 
    gallery.image("marco 1")
    gallery.button("marco 2") 
    gallery.image("marco 2")
    gallery.button("marco 3") 
    gallery.image("marco 3")

    gallery.button("toto 1") 
    gallery.image("toto 1")
    gallery.button("toto 2") 
    gallery.image("toto 2")
    gallery.button("toto 3") 
    gallery.image("toto 3")
    gallery.button("toto 4") 
    gallery.image("toto 4")
    gallery.button("toto 5") 
    gallery.image("toto 5")
    gallery.button("toto 6") 
    gallery.image("toto 6")

    gallery.button("iside 1") 
    gallery.image("iside 1")
    gallery.button("iside 2") 
    gallery.image("iside 2")
    gallery.button("iside 3") 
    gallery.image("iside 3")

    gallery.button("vita 1") 
    gallery.image("vita 1")
    gallery.button("vita 2") 
    gallery.image("vita 2")
    gallery.button("vita 3") 
    gallery.image("vita 3")

    gallery.button("wonder 1") 
    gallery.image("wonder 1")
    gallery.button("wonder 2") 
    gallery.image("wonder 2")
    gallery.button("wonder 3") 
    gallery.image("wonder 3")
    gallery.button("wonder 4") 
    gallery.image("wonder 4")
    gallery.button("wonder 5") 
    gallery.image("wonder 5")
    gallery.button("wonder 6") 
    gallery.image("wonder 6")

    gallery.button("mariarosa 1") 
    gallery.image("mariarosa 1")
    gallery.button("mariarosa 2") 
    gallery.image("mariarosa 2")
    gallery.button("mariarosa 3") 
    gallery.image("mariarosa 3")

    gallery.button("altro 1") 
    gallery.image("altro 1")
    gallery.button("altro 2") 
    gallery.image("altro 2")
    gallery.button("altro 3") 
    gallery.image("altro 3")
    gallery.button("altro 4") 
    gallery.image("altro 4")
    gallery.button("altro 5") 
    gallery.image("altro 5")
    gallery.button("altro 6") 
    gallery.image("altro 6")
    gallery.button("altro 7") 
    gallery.image("altro 7")
    gallery.button("altro 8") 
    gallery.image("altro 8")
    gallery.button("altro 9") 
    gallery.image("altro 9")
    gallery.button("altro 10") 
    gallery.image("altro 10")
    gallery.button("altro 11") 
    gallery.image("altro 11")
    gallery.button("altro 12") 
    gallery.image("altro 12")
    gallery.button("altro 13") 
    gallery.image("altro 13")
    gallery.button("altro 14") 
    gallery.image("altro 14")
    gallery.button("altro 15") 
    gallery.image("altro 15")
    gallery.button("altro 16") 
    gallery.image("altro 16")
    gallery.button("altro 17") 
    gallery.image("altro 17")
    gallery.button("altro 18") 
    gallery.image("altro 18")
    gallery.button("altro 19") 
    gallery.image("altro 19")
    gallery.button("altro 20") 
    gallery.image("altro 20")
    gallery.button("altro 21") 
    gallery.image("altro 21")
    gallery.button("altro 22") 
    gallery.image("altro 22")
    gallery.button("altro 23") 
    gallery.image("altro 23")
    gallery.button("altro 24") 
    gallery.image("altro 24")
    gallery.button("altro 25") 
    gallery.image("altro 25")
    gallery.button("altro 26") 
    gallery.image("altro 26")
    gallery.button("altro 27") 
    gallery.image("altro 27")


screen album:
    tag menu
    hbox:
        xalign 0.5
        yalign 0.5
        spacing 40
        grid 3 22:
            spacing 50
            add gallery.make_button(name="fiore 1",unlocked="album/small/fiore small 1.jpg") 
            add gallery.make_button(name="fiore 2",unlocked="album/small/fiore small 2.jpg")
            add gallery.make_button(name="fiore 3",unlocked="album/small/fiore small 3.jpg")
            
            add gallery.make_button(name="luna 1",unlocked="album/small/luna small 1.jpg") 
            add gallery.make_button(name="luna 2",unlocked="album/small/luna small 2.jpg")
            add gallery.make_button(name="luna 3",unlocked="album/small/luna small 3.jpg")

            add gallery.make_button(name="micia 1", unlocked="album/small/micia small 1.jpg")
            add gallery.make_button(name="micia 2", unlocked="album/small/micia small 2.jpg")
            add gallery.make_button(name="micia 3", unlocked="album/small/micia small 3.jpg")

            add gallery.make_button(name="pinpin 1", unlocked="album/small/pinpin small 1.jpg")
            add gallery.make_button(name="pinpin 2", unlocked="album/small/pinpin small 2.jpg")
            add gallery.make_button(name="pinpin 3", unlocked="album/small/pinpin small 3.jpg")

            add gallery.make_button(name="valerio 1", unlocked="album/small/valerio small 1.jpg")
            add gallery.make_button(name="valerio 2", unlocked="album/small/valerio small 2.jpg")
            add gallery.make_button(name="valerio 3", unlocked="album/small/valerio small 3.jpg")

            add gallery.make_button(name="marco 1", unlocked="album/small/marco small 1.jpg")
            add gallery.make_button(name="marco 2", unlocked="album/small/marco small 2.jpg")
            add gallery.make_button(name="marco 3", unlocked="album/small/marco small 3.jpg")

            add gallery.make_button(name="toto 1", unlocked="album/small/toto small 1.jpg")
            add gallery.make_button(name="toto 2", unlocked="album/small/toto small 2.jpg")
            add gallery.make_button(name="toto 3", unlocked="album/small/toto small 3.jpg")
            add gallery.make_button(name="toto 4", unlocked="album/small/toto small 4.jpg")
            add gallery.make_button(name="toto 5", unlocked="album/small/toto small 5.jpg")
            add gallery.make_button(name="toto 6", unlocked="album/small/toto small 6.jpg")

            add gallery.make_button(name="iside 1", unlocked="album/small/iside small 1.jpg")
            add gallery.make_button(name="iside 2", unlocked="album/small/iside small 2.jpg")
            add gallery.make_button(name="iside 3", unlocked="album/small/iside small 3.jpg")

            add gallery.make_button(name="vita 1", unlocked="album/small/vita small 1.jpg")
            add gallery.make_button(name="vita 2", unlocked="album/small/vita small 2.jpg")
            add gallery.make_button(name="vita 3", unlocked="album/small/vita small 3.jpg")

            add gallery.make_button(name="wonder 1", unlocked="album/small/wonder small 1.jpg")
            add gallery.make_button(name="wonder 2", unlocked="album/small/wonder small 2.jpg")
            add gallery.make_button(name="wonder 3", unlocked="album/small/wonder small 3.jpg")
            add gallery.make_button(name="wonder 4", unlocked="album/small/wonder small 4.jpg")
            add gallery.make_button(name="wonder 5", unlocked="album/small/wonder small 5.jpg")
            add gallery.make_button(name="wonder 6", unlocked="album/small/wonder small 6.jpg")

            add gallery.make_button(name="mariarosa 1", unlocked="album/small/mariarosa small 1.jpg")
            add gallery.make_button(name="mariarosa 2", unlocked="album/small/mariarosa small 2.jpg")
            add gallery.make_button(name="mariarosa 3", unlocked="album/small/mariarosa small 3.jpg")

            add gallery.make_button(name="altro 1", unlocked="album/small/altro/altro small 1.jpg")
            add gallery.make_button(name="altro 2", unlocked="album/small/altro/altro small 2.jpg")
            add gallery.make_button(name="altro 3", unlocked="album/small/altro/altro small 3.jpg")
            add gallery.make_button(name="altro 4", unlocked="album/small/altro/altro small 4.jpg")
            add gallery.make_button(name="altro 5", unlocked="album/small/altro/altro small 5.jpg")
            add gallery.make_button(name="altro 6", unlocked="album/small/altro/altro small 6.jpg")
            add gallery.make_button(name="altro 7", unlocked="album/small/altro/altro small 7.jpg")
            add gallery.make_button(name="altro 8", unlocked="album/small/altro/altro small 8.jpg")
            add gallery.make_button(name="altro 9", unlocked="album/small/altro/altro small 9.jpg")
            add gallery.make_button(name="altro 10", unlocked="album/small/altro/altro small 10.jpg")
            add gallery.make_button(name="altro 11", unlocked="album/small/altro/altro small 11.jpg")
            add gallery.make_button(name="altro 12", unlocked="album/small/altro/altro small 12.jpg")
            add gallery.make_button(name="altro 13", unlocked="album/small/altro/altro small 13.jpg")
            add gallery.make_button(name="altro 14", unlocked="album/small/altro/altro small 14.jpg")
            add gallery.make_button(name="altro 15", unlocked="album/small/altro/altro small 15.jpg")
            add gallery.make_button(name="altro 16", unlocked="album/small/altro/altro small 16.jpg")
            add gallery.make_button(name="altro 17", unlocked="album/small/altro/altro small 17.jpg")
            add gallery.make_button(name="altro 18", unlocked="album/small/altro/altro small 18.jpg")
            add gallery.make_button(name="altro 19", unlocked="album/small/altro/altro small 19.jpg")
            add gallery.make_button(name="altro 20", unlocked="album/small/altro/altro small 20.jpg")
            add gallery.make_button(name="altro 21", unlocked="album/small/altro/altro small 21.jpg")
            add gallery.make_button(name="altro 22", unlocked="album/small/altro/altro small 22.jpg")
            add gallery.make_button(name="altro 23", unlocked="album/small/altro/altro small 23.jpg")
            add gallery.make_button(name="altro 24", unlocked="album/small/altro/altro small 24.jpg")
            add gallery.make_button(name="altro 25", unlocked="album/small/altro/altro small 25.jpg")
            add gallery.make_button(name="altro 26", unlocked="album/small/altro/altro small 26.jpg")
            add gallery.make_button(name="altro 27", unlocked="album/small/altro/altro small 27.jpg")

